// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientCard.Data;

#nullable disable

namespace PatientCard.Migrations
{
    [DbContext(typeof(PatientCardContext))]
    [Migration("20230322212704_User")]
    partial class User
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PatientCard.Areas.Identity.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PatientCard.Models.Analyze", b =>
                {
                    b.Property<int>("IdAnalyzes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnalyzes"));

                    b.Property<DateTime?>("DateAnalyzes")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorIdDoctor")
                        .HasColumnType("int");

                    b.Property<int?>("IdDepartament")
                        .HasColumnType("int");

                    b.Property<int?>("IdDoctor")
                        .HasColumnType("int");

                    b.Property<int?>("IdService")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdAnalyzes");

                    b.HasIndex("DoctorIdDoctor");

                    b.HasIndex("UserId");

                    b.ToTable("Analyze");
                });

            modelBuilder.Entity("PatientCard.Models.Anthropometry", b =>
                {
                    b.Property<int>("AnthropometryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnthropometryId"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnthropometryId");

                    b.HasIndex("UserId");

                    b.ToTable("Anthropometry");
                });

            modelBuilder.Entity("PatientCard.Models.Departament", b =>
                {
                    b.Property<int>("IdDepartament")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartament"));

                    b.Property<string>("AdressDepartament")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameDepartament")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeDepartament")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDepartament");

                    b.ToTable("Departament");
                });

            modelBuilder.Entity("PatientCard.Models.DisabilitySheet", b =>
                {
                    b.Property<int>("DisabilitySheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisabilitySheetId"));

                    b.Property<DateTime?>("DateOfSinging")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdDepartement")
                        .HasColumnType("int");

                    b.Property<int?>("IdDoctor")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DisabilitySheetId");

                    b.HasIndex("UserId");

                    b.ToTable("DisabilitySheet");
                });

            modelBuilder.Entity("PatientCard.Models.Doctor", b =>
                {
                    b.Property<int>("IdDoctor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDoctor"));

                    b.Property<string>("FullNameDoctor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureDoctor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDoctor");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("PatientCard.Models.Financing", b =>
                {
                    b.Property<int>("FinancingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinancingId"));

                    b.Property<string>("FinancingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FinancingId");

                    b.ToTable("Financing");
                });

            modelBuilder.Entity("PatientCard.Models.Glucose", b =>
                {
                    b.Property<int>("GlucoseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GlucoseId"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GlucoseId");

                    b.HasIndex("UserId");

                    b.ToTable("Glucose");
                });

            modelBuilder.Entity("PatientCard.Models.Hospital", b =>
                {
                    b.Property<int>("HospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HospitalId"));

                    b.Property<DateTime?>("DateDischarge")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReceipt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartamentId")
                        .HasColumnType("int");

                    b.Property<int?>("DoctorHospitalId")
                        .HasColumnType("int");

                    b.Property<int?>("InspectionHospitalId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OperationId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceptionId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Ward")
                        .HasColumnType("int");

                    b.HasKey("HospitalId");

                    b.HasIndex("UserId");

                    b.ToTable("Hospital");
                });

            modelBuilder.Entity("PatientCard.Models.InspectionHospital", b =>
                {
                    b.Property<int>("InspectionHospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InspectionHospitalId"));

                    b.Property<string>("Complaint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartamentId")
                        .HasColumnType("int");

                    b.Property<int?>("DoctorHospitalId")
                        .HasColumnType("int");

                    b.Property<string>("Inspection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspectionPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InspectionHospitalId");

                    b.HasIndex("UserId");

                    b.ToTable("InspectionHospital");
                });

            modelBuilder.Entity("PatientCard.Models.InspectionPoliclinic", b =>
                {
                    b.Property<int>("InspectionPoliclinicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InspectionPoliclinicId"));

                    b.Property<string>("AnamnesisDisease")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complaints")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Recommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InspectionPoliclinicId");

                    b.HasIndex("UserId");

                    b.ToTable("InspectionPoliclinics");
                });

            modelBuilder.Entity("PatientCard.Models.MedicalCar", b =>
                {
                    b.Property<int>("MedicalCarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalCarId"));

                    b.Property<DateTime?>("DateMedicalCar")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdDoctor")
                        .HasColumnType("int");

                    b.Property<int>("IdDoctorNavigationIdDoctor")
                        .HasColumnType("int");

                    b.Property<string>("IssueExit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceExit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonExit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultExit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MedicalCarId");

                    b.HasIndex("IdDoctorNavigationIdDoctor");

                    b.HasIndex("UserId");

                    b.ToTable("MedicalCar");
                });

            modelBuilder.Entity("PatientCard.Models.Operation", b =>
                {
                    b.Property<int>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperationId"));

                    b.Property<DateTime?>("DateOperation")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiagnosisOperation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("DurationOperation")
                        .HasColumnType("time");

                    b.Property<int?>("IdDepartamnet")
                        .HasColumnType("int");

                    b.Property<int?>("IdDoctorHospital")
                        .HasColumnType("int");

                    b.Property<int?>("IdFinancing")
                        .HasColumnType("int");

                    b.Property<int?>("IdService")
                        .HasColumnType("int");

                    b.Property<string>("ProtocolOperation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OperationId");

                    b.HasIndex("UserId");

                    b.ToTable("Operation");
                });

            modelBuilder.Entity("PatientCard.Models.Organization", b =>
                {
                    b.Property<int>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizationId"));

                    b.Property<int?>("DepartamentId")
                        .HasColumnType("int");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganizationId");

                    b.HasIndex("DepartamentId");

                    b.HasIndex("DoctorId");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("PatientCard.Models.Oxygen", b =>
                {
                    b.Property<int>("OxygenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OxygenId"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OxygenId");

                    b.HasIndex("UserId");

                    b.ToTable("Oxygen");
                });

            modelBuilder.Entity("PatientCard.Models.Polyclinic", b =>
                {
                    b.Property<int>("PolyclinicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolyclinicId"));

                    b.Property<int?>("AnalyzeId")
                        .HasColumnType("int");

                    b.Property<string>("Complaints")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartamentId")
                        .HasColumnType("int");

                    b.Property<int?>("FinancingId")
                        .HasColumnType("int");

                    b.Property<int?>("InspectionId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudyId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PolyclinicId");

                    b.HasIndex("UserId");

                    b.ToTable("Polyclinic");
                });

            modelBuilder.Entity("PatientCard.Models.Pressure", b =>
                {
                    b.Property<int>("PressureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PressureId"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PressureId");

                    b.HasIndex("UserId");

                    b.ToTable("Pressure");
                });

            modelBuilder.Entity("PatientCard.Models.Reception", b =>
                {
                    b.Property<int>("ReceptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceptionId"));

                    b.Property<int?>("AnalyzeId")
                        .HasColumnType("int");

                    b.Property<string>("AnamnesisDisease")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnamnesisLife")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Complaints")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartamentId")
                        .HasColumnType("int");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoctorHospitalId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("StudyId")
                        .HasColumnType("int");

                    b.Property<string>("TreatmentPlan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReceptionId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Reception");
                });

            modelBuilder.Entity("PatientCard.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<string>("CodeRecipe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateRecipe")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdDoctor")
                        .HasColumnType("int");

                    b.Property<string>("RecipeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("PatientCard.Models.Service", b =>
                {
                    b.Property<int>("IdService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdService"));

                    b.Property<string>("CodeService")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameService")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdService");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("PatientCard.Models.Stydy", b =>
                {
                    b.Property<int>("StydyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StydyId"));

                    b.Property<string>("Conclusion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartamentId")
                        .HasColumnType("int");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Done")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Protocol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StydyId");

                    b.HasIndex("UserId");

                    b.ToTable("Stydy");
                });

            modelBuilder.Entity("PatientCard.Models.Temperature", b =>
                {
                    b.Property<int>("TemperatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemperatureId"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TemperatureId");

                    b.HasIndex("UserId");

                    b.ToTable("Temperature");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PatientCard.Areas.Identity.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PatientCard.Areas.Identity.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientCard.Areas.Identity.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PatientCard.Areas.Identity.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientCard.Models.Analyze", b =>
                {
                    b.HasOne("PatientCard.Models.Doctor", "Doctor")
                        .WithMany("Analyzes")
                        .HasForeignKey("DoctorIdDoctor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientCard.Areas.Identity.Data.ApplicationUser", "User")
                        .WithMany("Analyze")
                        .HasForeignKey("UserId");

                    b.Navigation("Doctor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PatientCard.Models.Anthropometry", b =>
                {
                    b.HasOne("PatientCard.Areas.Identity.Data.ApplicationUser", "User")
                        .WithMany("Anthropometry")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PatientCard.Models.DisabilitySheet", b =>
                {
                    b.HasOne("PatientCard.Areas.Identity.Data.ApplicationUser", "User")
                        .WithMany("DisabilitySheet")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PatientCard.Models.Glucose", b =>
                {
                    b.HasOne("PatientCard.Areas.Identity.Data.ApplicationUser", "User")
                        .WithMany("Glucose")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PatientCard.Models.Hospital", b =>
                {
                    b.HasOne("PatientCard.Areas.Identity.Data.ApplicationUser", "User")
                        .WithMany("Hospital")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PatientCard.Models.InspectionHospital", b =>
                {
                    b.HasOne("PatientCard.Areas.Identity.Data.ApplicationUser", "User")
                        .WithMany("InspectionHospital")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PatientCard.Models.InspectionPoliclinic", b =>
                {
                    b.HasOne("PatientCard.Areas.Identity.Data.ApplicationUser", "User")
                        .WithMany("InspectionPoliclinic")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PatientCard.Models.MedicalCar", b =>
                {
                    b.HasOne("PatientCard.Models.Doctor", "IdDoctorNavigation")
                        .WithMany()
                        .HasForeignKey("IdDoctorNavigationIdDoctor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientCard.Areas.Identity.Data.ApplicationUser", "User")
                        .WithMany("MedicalCar")
                        .HasForeignKey("UserId");

                    b.Navigation("IdDoctorNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PatientCard.Models.Operation", b =>
                {
                    b.HasOne("PatientCard.Areas.Identity.Data.ApplicationUser", "User")
                        .WithMany("Operation")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PatientCard.Models.Organization", b =>
                {
                    b.HasOne("PatientCard.Models.Departament", "Departament")
                        .WithMany()
                        .HasForeignKey("DepartamentId");

                    b.HasOne("PatientCard.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.Navigation("Departament");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("PatientCard.Models.Oxygen", b =>
                {
                    b.HasOne("PatientCard.Areas.Identity.Data.ApplicationUser", "User")
                        .WithMany("Oxygen")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PatientCard.Models.Polyclinic", b =>
                {
                    b.HasOne("PatientCard.Areas.Identity.Data.ApplicationUser", "User")
                        .WithMany("Polyclinic")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PatientCard.Models.Pressure", b =>
                {
                    b.HasOne("PatientCard.Areas.Identity.Data.ApplicationUser", "User")
                        .WithMany("Pressure")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PatientCard.Models.Reception", b =>
                {
                    b.HasOne("PatientCard.Areas.Identity.Data.ApplicationUser", null)
                        .WithMany("Reception")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("PatientCard.Models.Recipe", b =>
                {
                    b.HasOne("PatientCard.Areas.Identity.Data.ApplicationUser", "User")
                        .WithMany("Recipe")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PatientCard.Models.Stydy", b =>
                {
                    b.HasOne("PatientCard.Areas.Identity.Data.ApplicationUser", "User")
                        .WithMany("Stydy")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PatientCard.Models.Temperature", b =>
                {
                    b.HasOne("PatientCard.Areas.Identity.Data.ApplicationUser", "User")
                        .WithMany("Temperature")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PatientCard.Areas.Identity.Data.ApplicationUser", b =>
                {
                    b.Navigation("Analyze");

                    b.Navigation("Anthropometry");

                    b.Navigation("DisabilitySheet");

                    b.Navigation("Glucose");

                    b.Navigation("Hospital");

                    b.Navigation("InspectionHospital");

                    b.Navigation("InspectionPoliclinic");

                    b.Navigation("MedicalCar");

                    b.Navigation("Operation");

                    b.Navigation("Oxygen");

                    b.Navigation("Polyclinic");

                    b.Navigation("Pressure");

                    b.Navigation("Reception");

                    b.Navigation("Recipe");

                    b.Navigation("Stydy");

                    b.Navigation("Temperature");
                });

            modelBuilder.Entity("PatientCard.Models.Doctor", b =>
                {
                    b.Navigation("Analyzes");
                });
#pragma warning restore 612, 618
        }
    }
}
